# Generated by Django 4.2.11 on 2024-04-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Subject', models.TextField(max_length=200)),
                ('Message', models.TextField(max_length=300)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(default=' ', max_length=200)),
                ('Required_Skills', models.TextField()),
                ('Required_Experience', models.CharField(max_length=200)),
                ('Job_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resumeform',
            fields=[
                ('Resume_No', models.AutoField(primary_key=True, serialize=False)),
                ('R_Name', models.CharField(default='No Name Found', max_length=122)),
                ('R_Email', models.CharField(default='default@mail.com', max_length=122)),
                ('Resumefile', models.FileField(default='', upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, default='default@mail.com', max_length=254, null=True)),
                ('Mobile_No', models.IntegerField(blank=True, default=9999999999, null=True)),
                ('Skills', models.TextField(default='No skills found', max_length=200)),
                ('Education', models.TextField(default='No education found', max_length=200)),
                ('Experience', models.TextField(default='No experience found', max_length=200)),
                ('Resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.resumeform')),
            ],
        ),
        migrations.CreateModel(
            name='Matched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Extracted_skills', models.TextField(default='No skills extracted')),
                ('Required_skills', models.TextField(default='No required skills provided')),
                ('Matched_skills', models.TextField(default='No matched skills')),
                ('Percent_matched', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, default='default@mail.com', max_length=254, null=True)),
                ('Mobile_No', models.IntegerField(blank=True, default=9999999999, null=True)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.jobdescription')),
                ('Resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.resumeform')),
            ],
        ),
    ]
