# Generated by Django 5.0.4 on 2024-04-05 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Subject', models.TextField(max_length=200)),
                ('Message', models.TextField(max_length=300)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('Title', models.CharField(max_length=200)),
                ('Required_Skills', models.TextField()),
                ('Required_Experience', models.CharField(max_length=200)),
                ('Job_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resumeform',
            fields=[
                ('Resume_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Resumefile', models.FileField(default='', upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(default='default@mail.com', max_length=254)),
                ('Mobile_No', models.IntegerField(default='9999999999')),
                ('Skills', models.TextField(default='No skills found', max_length=200)),
                ('Education', models.TextField(default='No education found', max_length=200)),
                ('Experience', models.TextField(default='No experience found', max_length=200)),
                ('Resume_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.resumeform')),
            ],
        ),
        migrations.CreateModel(
            name='Matched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Extracted_skills', models.TextField(default='No skills extracted')),
                ('Required_skills', models.TextField(default='No required skills provided')),
                ('Matched_skills', models.TextField(default='No matched skills')),
                ('Percent_matched', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.jobdescription')),
                ('Resume_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.resumeform')),
            ],
        ),
    ]
