# Generated by Django 4.1.7 on 2023-09-01 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Required_Skills', models.TextField()),
                ('Requires_Experience', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('Resume_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254, verbose_name='')),
                ('Mobile_No', models.IntegerField()),
                ('Skills', models.TextField(max_length=200)),
                ('Education', models.TextField(max_length=200)),
                ('Experience', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Matched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Extracted_skills', models.TextField()),
                ('Resuired_skills', models.TextField()),
                ('Matched_skills', models.TextField()),
                ('Percent_matched', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.resumedata')),
            ],
        ),
    ]
