# Generated by Django 4.1.7 on 2023-09-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Subject', models.TextField(max_length=200)),
                ('Message', models.TextField(max_length=300)),
                ('Date', models.DateField()),
            ],
        ),
    ]
