# Generated by Django 5.0.4 on 2024-04-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matched',
            old_name='Job_id',
            new_name='Job',
        ),
        migrations.RenameField(
            model_name='matched',
            old_name='Resume_No',
            new_name='Resume',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='Resume_No',
            new_name='Resume',
        ),
    ]
