# Generated by Django 5.0.4 on 2024-04-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_job_id_matched_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='Job_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resumeform',
            name='Resume_No',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
