# Generated by Django 4.1 on 2023-10-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_resumeform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeform',
            old_name='resumefile',
            new_name='Resumefile',
        ),
    ]
