# Generated by Django 5.0.4 on 2024-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_jobdescription_job_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='Description',
            field=models.TextField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='resumeform',
            name='Email',
            field=models.CharField(default='default@mail.com', max_length=122),
        ),
        migrations.AlterField(
            model_name='resumeform',
            name='Name',
            field=models.CharField(default='No Name Found', max_length=122),
        ),
    ]
