# Generated by Django 5.0.4 on 2024-04-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_jobdescription_description_alter_resumeform_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='Mobile_No',
            field=models.IntegerField(default=9999999999),
        ),
    ]
