# Generated by Django 5.0.4 on 2024-04-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_resumedata_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='Mobile_No',
            field=models.IntegerField(blank=True, default=9999999999, null=True),
        ),
    ]
