# Generated by Django 5.0.4 on 2024-04-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_resumedata_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeform',
            old_name='Email',
            new_name='R_Email',
        ),
        migrations.RenameField(
            model_name='resumeform',
            old_name='Name',
            new_name='R_Name',
        ),
    ]
