# Generated by Django 5.0.4 on 2024-04-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_resumedata_email_alter_resumedata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='matched',
            name='Email',
            field=models.EmailField(blank=True, default='default@mail.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='matched',
            name='Mobile_No',
            field=models.IntegerField(blank=True, default=9999999999, null=True),
        ),
        migrations.AddField(
            model_name='matched',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matched',
            name='Resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.resumedata'),
        ),
    ]
