# Generated by Django 5.0.4 on 2024-04-09 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_matched_email_matched_mobile_no_matched_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matched',
            name='Resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.resumeform'),
        ),
    ]
